// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6WvzM7H8JcX-nm_w3JfChwNThVJCsiLk',
    appId: '1:254374145600:web:3460ec1a330df69dd5b9a5',
    messagingSenderId: '254374145600',
    projectId: 'lab-11-mp-9da84',
    authDomain: 'lab-11-mp-9da84.firebaseapp.com',
    storageBucket: 'lab-11-mp-9da84.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgW-MzUamE5l2ijnE6p88k2hln5h2gOBY',
    appId: '1:254374145600:android:f01b0da755d262c1d5b9a5',
    messagingSenderId: '254374145600',
    projectId: 'lab-11-mp-9da84',
    storageBucket: 'lab-11-mp-9da84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy0w7LPrk0yWAw-Aue8dZUDn6IhWHVCMg',
    appId: '1:254374145600:ios:d90645ba79893525d5b9a5',
    messagingSenderId: '254374145600',
    projectId: 'lab-11-mp-9da84',
    storageBucket: 'lab-11-mp-9da84.appspot.com',
    iosBundleId: 'com.example.lab11Main',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy0w7LPrk0yWAw-Aue8dZUDn6IhWHVCMg',
    appId: '1:254374145600:ios:4638a0eaf6c0856dd5b9a5',
    messagingSenderId: '254374145600',
    projectId: 'lab-11-mp-9da84',
    storageBucket: 'lab-11-mp-9da84.appspot.com',
    iosBundleId: 'com.example.lab11Main.RunnerTests',
  );
}
